name: Update Google News Sitemap

on:
  schedule:
    - cron: '30 * * * *'
  push:
    branches:
      - main
    paths:
      - 'generate_sitemap.py'
      - 'index_news.py'
      - 'requirements.txt'
      - '.github/workflows/update_sitemap.yml'
  workflow_dispatch:

# Empêche deux versions de courir en même temps et de s'annuler
concurrency:
  group: sitemap-locking-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... la suite de tes étapes (checkout, setup python, etc.)
